package gamesmanager;
// Generated 30/08/2018 12:31:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Plataforma generated by hbm2java
 */
public class Plataforma  implements java.io.Serializable {


     private Integer pkCod;
     private Estudio estudio;
     private String nome;
     private boolean ehPortatil;
     private Set jogos = new HashSet(0);

    public Plataforma() {
    }

	
    public Plataforma(Estudio estudio, String nome, boolean ehPortatil) {
        this.estudio = estudio;
        this.nome = nome;
        this.ehPortatil = ehPortatil;
    }
    public Plataforma(Estudio estudio, String nome, boolean ehPortatil, Set jogos) {
       this.estudio = estudio;
       this.nome = nome;
       this.ehPortatil = ehPortatil;
       this.jogos = jogos;
    }
   
    public Integer getPkCod() {
        return this.pkCod;
    }
    
    public void setPkCod(Integer pkCod) {
        this.pkCod = pkCod;
    }
    public Estudio getEstudio() {
        return this.estudio;
    }
    
    public void setEstudio(Estudio estudio) {
        this.estudio = estudio;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public boolean isEhPortatil() {
        return this.ehPortatil;
    }
    
    public void setEhPortatil(boolean ehPortatil) {
        this.ehPortatil = ehPortatil;
    }
    public Set getJogos() {
        return this.jogos;
    }
    
    public void setJogos(Set jogos) {
        this.jogos = jogos;
    }




}


