package gamesmanager;
// Generated 30/08/2018 12:31:40 by Hibernate Tools 4.3.1



/**
 * UsuarioHasJogoId generated by hbm2java
 */
public class UsuarioHasJogoId  implements java.io.Serializable {


     private String usuarioPkCpf;
     private int jogoPkCod;

    public UsuarioHasJogoId() {
    }

    public UsuarioHasJogoId(String usuarioPkCpf, int jogoPkCod) {
       this.usuarioPkCpf = usuarioPkCpf;
       this.jogoPkCod = jogoPkCod;
    }
   
    public String getUsuarioPkCpf() {
        return this.usuarioPkCpf;
    }
    
    public void setUsuarioPkCpf(String usuarioPkCpf) {
        this.usuarioPkCpf = usuarioPkCpf;
    }
    public int getJogoPkCod() {
        return this.jogoPkCod;
    }
    
    public void setJogoPkCod(int jogoPkCod) {
        this.jogoPkCod = jogoPkCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioHasJogoId) ) return false;
		 UsuarioHasJogoId castOther = ( UsuarioHasJogoId ) other; 
         
		 return ( (this.getUsuarioPkCpf()==castOther.getUsuarioPkCpf()) || ( this.getUsuarioPkCpf()!=null && castOther.getUsuarioPkCpf()!=null && this.getUsuarioPkCpf().equals(castOther.getUsuarioPkCpf()) ) )
 && (this.getJogoPkCod()==castOther.getJogoPkCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsuarioPkCpf() == null ? 0 : this.getUsuarioPkCpf().hashCode() );
         result = 37 * result + this.getJogoPkCod();
         return result;
   }   


}


